# Generated by Django 5.0.3 on 2024-04-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_image1_product_image2_product_image3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='your_upload_directory/'),
        ),
    ]
