# Generated by Django 5.0.3 on 2024-04-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
