# Generated by Django 5.0.3 on 2024-04-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
